Analog Clock
IOSD/IOSD-BPIT-Hacktoberfest-2022 pull request #108
Opened 2022-10-14 20:44 UTC by MAYURIKOTHARI299

2022-10-15 02:52 UTC, KhushbooGupta2111 commented
Changing it to analog clock second since we already have project of that.

2022-10-15 02:56 UTC, KhushbooGupta2111 approved these changes

2022-10-15 06:47 UTC, hiferli requested changes
Great work doing this project!
However, can you create a folder named Analog Clock (Second) and add these files to that folder?
Currently, these files are in WebDev/Frontend; hence, it would be better that this project has a different folder.
An additional README file describing your project would be an excellent add-on to the project.

2022-10-16 10:33 UTC, KhushbooGupta2111 commented
@MAYURIKOTHARI299, raise another PR for both Mutiple stacks and Analog clock.

2022-10-16 10:33 UTC, closed without merging