job_application_form
IOSD/IOSD-BPIT-Hacktoberfest-2022 pull request #114
Opened 2022-10-15 07:17 UTC by vik1456

This is a Job application form made using only html and css

2022-10-15 07:20 UTC, hiferli requested changes
Can you make a subfolder in the WebDev/Frontend directory and add those files over there?
Thanks

2022-10-15 07:36 UTC, KhushbooGupta2111 approved these changes

2022-10-15 07:37 UTC, KhushbooGupta2111 commented
@hiferli, I guess it's inside the frontend folder

2022-10-19 10:47 UTC, KhushbooGupta2111 approved these changes

2022-10-19 10:48 UTC, merged