GestureDetection
IOSD/IOSD-BPIT-Hacktoberfest-2022 pull request #120
Opened 2022-10-15 14:37 UTC by Pallavipanjla

Gesture Detection using cv2 and mediapipe.

2022-10-15 14:45 UTC, KhushbooGupta2111 approved these changes

2022-10-15 14:46 UTC, KhushbooGupta2111 commented
Adding a readme file would be better

2022-10-16 10:15 UTC, hiferli requested changes
Your file name is GestureDetection (comma) py
Please change the comma to the dot.

Thank You
![image](https://user-images.githubusercontent.com/91693371/196029847-69c31fc1-d0d0-4095-ac58-de9883e6a559.png)

2022-10-19 10:48 UTC, KhushbooGupta2111 approved these changes

2022-10-19 10:56 UTC, merged