Movie recommendation system
IOSD/IOSD-BPIT-Hacktoberfest-2022 pull request #143
Opened 2022-10-18 16:49 UTC by Shinjini2002

2022-10-18 18:41 UTC, hiferli approved these changes

2022-10-18 18:42 UTC, hiferli requested changes
Can you shift this Python Notebook to the respective directory?
Currently it is placed in the home directory.

Thanks

2022-10-19 06:19 UTC, KhushbooGupta2111 approved these changes

2022-10-30 15:42 UTC, KhushbooGupta2111 approved these changes

2022-10-30 15:42 UTC, hiferli approved these changes

2022-10-30 15:42 UTC, merged